[2025-08-02T17:49:21.029+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-02T17:49:07+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
