[2025-08-04T13:16:40.753+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T13:16:41.102+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T13:16:41.214+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T13:16:41.267+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T13:16:41.269+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T13:16:41.364+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-03 00:00:00+00:00
[2025-08-04T13:16:41.437+0000] {standard_task_runner.py:60} INFO - Started process 103 to run task
[2025-08-04T13:16:41.453+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'scheduled__2025-08-03T00:00:00+00:00', '--job-id', '193', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpf7_wbrqv']
[2025-08-04T13:16:41.471+0000] {standard_task_runner.py:88} INFO - Job 193: Subtask load_to_redshift
[2025-08-04T13:16:42.102+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T13:16:42.139+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [running]> on host dbc46d35c6dd
[2025-08-04T13:16:42.785+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T00:00:00+00:00'
[2025-08-04T13:16:42.849+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T13:16:42.880+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T13:16:42.882+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T13:16:42.929+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-04T13:16:42.977+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-04T13:16:42.979+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T13:16:42.984+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-04T13:16:46.968+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.
[2025-08-04T13:16:47.020+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250803T000000, start_date=20250804T131641, end_date=20250804T131647
[2025-08-04T13:16:47.087+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 193 for task load_to_redshift (An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.; 103)
[2025-08-04T13:16:47.188+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T13:16:47.231+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T14:48:22.186+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:22.669+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:23.069+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T14:48:23.213+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T14:48:23.233+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T14:48:23.461+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-03 00:00:00+00:00
[2025-08-04T14:48:23.530+0000] {standard_task_runner.py:60} INFO - Started process 741 to run task
[2025-08-04T14:48:23.575+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'scheduled__2025-08-03T00:00:00+00:00', '--job-id', '51', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_grhpx1y']
[2025-08-04T14:48:23.586+0000] {standard_task_runner.py:88} INFO - Job 51: Subtask load_to_redshift
[2025-08-04T14:48:24.077+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T14:48:24.150+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [running]> on host 9edf237adf6e
[2025-08-04T14:48:25.142+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T00:00:00+00:00'
[2025-08-04T14:48:25.234+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T14:48:25.270+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T14:48:25.271+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T14:48:25.360+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-04T14:48:25.417+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-04T14:48:25.421+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T14:48:33.936+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.
[2025-08-04T14:48:33.996+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250803T000000, start_date=20250804T144823, end_date=20250804T144833
[2025-08-04T14:48:34.067+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 51 for task load_to_redshift (An error occurred (ValidationException) when calling the ExecuteStatement operation: Redshift endpoint is not available.; 741)
[2025-08-04T14:48:34.202+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-04T14:48:34.244+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-04T16:30:30.353+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:30:30.537+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:30:30.671+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T16:30:30.707+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [queued]>
[2025-08-04T16:30:30.709+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-04T16:30:30.821+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-03 00:00:00+00:00
[2025-08-04T16:30:30.884+0000] {standard_task_runner.py:60} INFO - Started process 2216 to run task
[2025-08-04T16:30:30.979+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'scheduled__2025-08-03T00:00:00+00:00', '--job-id', '93', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp5sfe52ce']
[2025-08-04T16:30:30.995+0000] {standard_task_runner.py:88} INFO - Job 93: Subtask load_to_redshift
[2025-08-04T16:30:31.242+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=scheduled__2025-08-03T00:00:00+00:00/task_id=load_to_redshift permission to 509
[2025-08-04T16:30:31.295+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift scheduled__2025-08-03T00:00:00+00:00 [running]> on host 9edf237adf6e
[2025-08-04T16:30:31.907+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-03T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-03T00:00:00+00:00'
[2025-08-04T16:30:31.943+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T16:30:31.976+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-04T16:30:31.983+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T16:30:32.022+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-04T16:30:32.043+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-04T16:30:32.044+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-04T16:30:35.849+0000] {redshift_data.py:113} INFO - Polling statement 975fd4b7-aec5-44e6-9c74-851cb35c7f68
[2025-08-04T16:30:36.196+0000] {redshift_data.py:129} INFO - Query STARTED
[2025-08-04T16:29:42.177+0000] {redshift_data.py:113} INFO - Polling statement 975fd4b7-aec5-44e6-9c74-851cb35c7f68
[2025-08-04T16:29:42.530+0000] {redshift_data.py:121} INFO - Processed 0 rows
[2025-08-04T16:29:42.533+0000] {s3_to_redshift.py:197} INFO - COPY command complete...
[2025-08-04T16:29:42.562+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250803T000000, start_date=20250804T163030, end_date=20250804T162942
[2025-08-04T16:31:51.563+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-08-04T16:31:51.589+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
