[2025-08-02T00:09:49.181+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T00:08:08.108500+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T00:09:49.254+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T00:08:08.108500+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T00:09:49.321+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T00:08:08.108500+00:00 [queued]>
[2025-08-02T00:09:49.342+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T00:08:08.108500+00:00 [queued]>
[2025-08-02T00:09:49.343+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-02T00:09:49.379+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 00:08:08.108500+00:00
[2025-08-02T00:09:49.395+0000] {standard_task_runner.py:60} INFO - Started process 108 to run task
[2025-08-02T00:09:49.404+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T00:08:08.108500+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_uji6l1k']
[2025-08-02T00:09:49.410+0000] {standard_task_runner.py:88} INFO - Job 65: Subtask load_to_redshift
[2025-08-02T00:09:49.552+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T00:08:08.108500+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T00:09:49.579+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T00:08:08.108500+00:00 [running]> on host f2527419f673
[2025-08-02T00:09:49.820+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T00:08:08.108500+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T00:08:08.108500+00:00'
[2025-08-02T00:09:49.846+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T00:09:49.862+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T00:09:49.864+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T00:09:49.894+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T00:09:49.911+0000] {base_aws.py:581} WARNING - Unable to find AWS Connection ID 'redshift_default', switching to empty.
[2025-08-02T00:09:49.912+0000] {base_aws.py:161} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name=None). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-08-02T00:09:51.523+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 989, in _make_api_call
    http, parsed_response = self._make_request(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1015, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 198, in _send_request
    request = self.create_request(request_dict, operation_model)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in create_request
    self._event_emitter.emit(
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/hooks.py", line 239, in _emit
    response = handler(**kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/signers.py", line 105, in handler
    return self.sign(operation_name, request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/signers.py", line 195, in sign
    auth.add_auth(request)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials
[2025-08-02T00:09:51.541+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T000808, start_date=20250802T000949, end_date=20250802T000951
[2025-08-02T00:09:51.565+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 65 for task load_to_redshift (Unable to locate credentials; 108)
[2025-08-02T00:09:51.619+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T00:09:51.657+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
