[2025-08-01T23:02:37.778+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-01T20:53:47.782452+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
