[2025-08-01T19:37:14.220+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-01T19:38:04.315599+00:00 [queued]> finished (success) although the task says it's queued. (Info: None) Was the task killed externally?
