[2025-08-02T01:16:06.798+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:16:06.965+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:16:07.117+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [queued]>
[2025-08-02T01:16:07.162+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [queued]>
[2025-08-02T01:16:07.171+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 4
[2025-08-02T01:16:07.223+0000] {taskinstance.py:2191} INFO - Executing <Task(S3ToRedshiftOperator): load_to_redshift> on 2025-08-02 01:09:53.940652+00:00
[2025-08-02T01:16:07.263+0000] {standard_task_runner.py:60} INFO - Started process 1052 to run task
[2025-08-02T01:16:07.288+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_redshift', 'manual__2025-08-02T01:09:53.940652+00:00', '--job-id', '86', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmp_sh_so5l']
[2025-08-02T01:16:07.304+0000] {standard_task_runner.py:88} INFO - Job 86: Subtask load_to_redshift
[2025-08-02T01:16:07.535+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-02T01:09:53.940652+00:00/task_id=load_to_redshift permission to 509
[2025-08-02T01:16:07.557+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_redshift manual__2025-08-02T01:09:53.940652+00:00 [running]> on host f2527419f673
[2025-08-02T01:16:07.866+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-08-02T01:09:53.940652+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-02T01:09:53.940652+00:00'
[2025-08-02T01:16:07.897+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:16:07.920+0000] {base.py:83} INFO - Using connection ID 'aws_default' for task execution.
[2025-08-02T01:16:07.929+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='aws_default', conn_type='aws') credentials retrieved from login and password.
[2025-08-02T01:16:07.966+0000] {s3_to_redshift.py:192} INFO - Executing COPY command...
[2025-08-02T01:16:08.015+0000] {base.py:83} INFO - Using connection ID 'redshift_default' for task execution.
[2025-08-02T01:16:08.017+0000] {warnings.py:109} WARNING - <string>:9: UserWarning: AWS Connection (conn_id='redshift_default', conn_type='redshift') expected connection type 'aws', got 'redshift'. This connection might not work correctly. Please use Amazon Web Services Connection type.

[2025-08-02T01:16:08.018+0000] {connection_wrapper.py:378} INFO - AWS Connection (conn_id='redshift_default', conn_type='redshift') credentials retrieved from login and password.
[2025-08-02T01:16:08.020+0000] {warnings.py:109} WARNING - <string>:9: AirflowProviderDeprecationWarning: Host tf-redshift-cluster.ci896s3qzt6h.eu-west-1.redshift.amazonaws.com:5439/dev_db specified in the connection is not used. Please, set it on extra['endpoint_url'] instead

[2025-08-02T01:16:11.729+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/transfers/s3_to_redshift.py", line 194, in execute
    redshift_hook.execute_query(sql=sql, **self.redshift_data_api_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/amazon/aws/hooks/redshift_data.py", line 99, in execute_query
    resp = self.conn.execute_statement(**trim_none_values(kwargs))
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 553, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/botocore/client.py", line 1009, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.
[2025-08-02T01:16:11.750+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_redshift, execution_date=20250802T010953, start_date=20250802T011607, end_date=20250802T011611
[2025-08-02T01:16:11.785+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 86 for task load_to_redshift (An error occurred (UnrecognizedClientException) when calling the ExecuteStatement operation: The security token included in the request is invalid.; 1052)
[2025-08-02T01:16:11.843+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-02T01:16:11.902+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
