[2025-08-04T14:46:56.192+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: cdr_pipeline.load_to_s3 scheduled__2025-07-28T00:00:00+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
