[2025-08-01T05:46:50.275+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T05:46:44.996560+00:00/task_id=load_to_s3 permission to 509
[2025-08-01T05:46:50.372+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T05:46:44.996560+00:00/task_id=load_to_s3 permission to 509
[2025-08-01T05:46:50.431+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-01T05:46:44.996560+00:00 [queued]>
[2025-08-01T05:46:50.443+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-01T05:46:44.996560+00:00 [queued]>
[2025-08-01T05:46:50.447+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-08-01T05:46:50.466+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_s3> on 2025-08-01 05:46:44.996560+00:00
[2025-08-01T05:46:50.476+0000] {standard_task_runner.py:60} INFO - Started process 92 to run task
[2025-08-01T05:46:50.487+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'cdr_pipeline', 'load_to_s3', 'manual__2025-08-01T05:46:44.996560+00:00', '--job-id', '109', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpnq7o5ub6']
[2025-08-01T05:46:50.490+0000] {standard_task_runner.py:88} INFO - Job 109: Subtask load_to_s3
[2025-08-01T05:46:50.610+0000] {logging_mixin.py:188} INFO - Changing /opt/***/logs/dag_id=cdr_pipeline/run_id=manual__2025-08-01T05:46:44.996560+00:00/task_id=load_to_s3 permission to 509
[2025-08-01T05:46:50.631+0000] {task_command.py:423} INFO - Running <TaskInstance: cdr_pipeline.load_to_s3 manual__2025-08-01T05:46:44.996560+00:00 [running]> on host 0a803ed78160
[2025-08-01T05:46:50.799+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='cdr_pipeline' AIRFLOW_CTX_TASK_ID='load_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2025-08-01T05:46:44.996560+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-01T05:46:44.996560+00:00'
[2025-08-01T05:46:50.803+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
TypeError: load_to_s3() missing 1 required positional argument: 's3_path'
[2025-08-01T05:46:50.819+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=cdr_pipeline, task_id=load_to_s3, execution_date=20250801T054644, start_date=20250801T054650, end_date=20250801T054650
[2025-08-01T05:46:50.845+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 109 for task load_to_s3 (load_to_s3() missing 1 required positional argument: 's3_path'; 92)
[2025-08-01T05:46:50.867+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-01T05:46:50.897+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
